apiVersion: v1
kind: Service
metadata:
  name: ml-serving-service
  namespace: default
  labels:
    app: ml-serving-app
spec:
  type: NodePort
  selector:
    app: ml-serving-app
  ports:
    - name: http        # Required for ServiceMonitor to work!
      port: 8000
      targetPort: 8000
      nodePort: 30080
